# Generated by Django 6.0.6 on 2026-06-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_length', models.FloatField(help_text='Inner length in cm')),
                ('internal_width', models.FloatField(help_text='Inner width in cm')),
                ('internal_height', models.FloatField(help_text='Inner height in cm')),
                ('max_weight', models.FloatField(help_text='Maximum weight capacity in kg')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost in ₹', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(help_text='Length in cm')),
                ('width', models.FloatField(help_text='Width in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_weight', models.FloatField(help_text='Total order weight (product.weight * quantity)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxes.box')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.product')),
            ],
        ),
    ]
